teamStats/config/routes.rb
Rails.application.routes.draw do
  resources :teams
  root 'teams#index'
end

teamStats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

teamStats/app/models/team.rb
class Team < ApplicationRecord
end

teamStats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

teamStats/app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  before_action :find_team, only: [:show, :edit, :update, :destroy]

  def index
  	@teams = Team.all
  end

  def new
  	@team = Team.new
  end

  def show
  end

  def create
  	@team = Team.new (team_params)

  	if @team.save
  		redirect_to @team
  	else
  		render 'new'
  	end
  end

  def edit
  end

  def update
  	if @team.update(team_params)
  		redirect_to @team
  	else
  		render 'edit'
  	end
  end

  def destroy
  	@team.destroy
  	redirect_to root_path
  end

  private

  def team_params
  	params.require(:team).permit(:name, :ground, :capacity, :manager, :website)
  end

  def find_team
  	@team = Team.find(params[:id])
  end


end

teamStats/app/helpers/application_helper.rb
module ApplicationHelper
end

teamStats/app/helpers/teams_helper.rb
module TeamsHelper
end

teamStats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeamStats</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= link_to "Home", root_path %><br>
  <%= link_to "Create New Team", new_team_path %>

    <%= yield %>
  </body>
</html>